### ISSUE TITLE
Rendering CJK Text and Characters

### ISSUE THREAD

**Issue by blazer2k1** [justinmeiners/stb-truetype-example#7]
Can you give an example on how to render unicode font characters like CJK?

I'm using Microsoft YaHei to load font, but no clue where to start.

**Comment by Nivdc** [comment]
This is simple, you only need to decode the UTF8 characters into the Codepoint used by the font file and replace `word[i]`.

[stb-truetype-example-CJK.zip](https://github.com/justinmeiners/stb-truetype-example/files/11740598/stb-truetype-example-CJK.zip)

**Comment by blazer2k1** [comment]
@Nivdc thanks, so the line height serves as the font size?

**Comment by Nivdc** [comment]
@blazer2k1 

Yes, the line height is indeed used as the font size.

There is an easy way to answer your question, just change the value and see what happens.

**Comment by blazer2k1** [comment]
Thanks, works great.

**Comment by justinmeiners** [comment]
@Nivdc anything you want to add to repo?

**Comment by Nivdc** [comment]
@justinmeiners 

I'm not sure, adding too much code might overcomplicate the example.🤔
